### PR TITLE
Add browser compatibility table to README

### LINKED ISSUE #98: What's wrong with Netflix?
Netflix is the most used streaming service, so it is the most important streaming service for getting working. What is currently preventing adblocking from working on Netflix, and what are steps we can take to fix it?

### PR DESCRIPTION
**Pull request by smsilva98**
Closes #98
Enhanced the README documentation by introducing a new table listing browser compatibility. This update complements the existing table, which previously only showed Android compatibility, providing a more comprehensive overview of the project's platform support. Additionally, added configuration for JetBrains IDEs and updated the version-mismatched package-lock.json file to match the version stated in package.json.

### CODE REVIEW

**Comment by Dreamlinerm** [comment]
There already is a compatibility 
image

**Comment by Dreamlinerm** [comment]
i put it above the android compatibility now

**Comment by smsilva98** [comment]
I feel like this would have been more clear and consistent with how the README is currently written

image

**Comment by Dreamlinerm** [comment]
hmm yes ok maybe you are right i will copy it in because you have a lot stuff not ignored

**Comment by smsilva98** [comment]
The other stuff is important for people using JetBrains IDEs and fixes an issue with the package-lock.json

**Comment by Dreamlinerm** [comment]
changed in 2110365da12aafc51574e074645d55f2dd212695

**Comment by Dreamlinerm** [comment]
yeah i probably should also have git ignored .vscode

**Comment by smsilva98** [comment]
I would say it is best practice to leave it in because you can enforce code-style guidelines and other things through those files

**Comment by Dreamlinerm** [comment]
hmm ok i will merge it, but i have the prettierrc file to enforce code-style

**Review by Dreamlinerm — COMMENTED** [review]
look ok

**Review by Dreamlinerm — APPROVED** [review]

**Comment by smsilva98** [comment]
Thank You

**Pull request merged**
