### PR TITLE
enable web-ext chrome support

### PR DESCRIPTION
**Pull request by SirNiklax**

### CODE REVIEW

**Comment by Dreamlinerm** [comment]
@SirNiklax why did you close it? did you make a mistake?

**Comment by Dreamlinerm** [comment]
I just have the local addon permanantly loaded into chrome thats why i did not use chrome web-ext

**Comment by Dreamlinerm** [comment]
I saw web-ext lint doesn't work for chrome because of v3 but the other stuff i added

**Comment by SirNiklax** [comment]
The problem is that chrome does not activate DRM while being controlled. I have to find a way to pass an argument to chrome.

**Comment by Dreamlinerm** [comment]
ah maybe you can set up a profile like on chrome?

**Comment by Dreamlinerm** [comment]
--chromium-profile=$Path does work, but it won't keep you signed in to the websites, so I would rather just refresh the add-on manually.

**Pull request closed without merging**
