### PR TITLE
Added - Brazilian Portuguese Localization

### PR DESCRIPTION
**Pull request by andercard0**
Added Brazilian Portuguese translation for both Mozilla and Chrome, untested. hope I did not broke anything.

Thanks for the great add-on.

### CODE REVIEW

**Comment by Dreamlinerm** [comment]
let me see if its ok

**Comment by Dreamlinerm** [comment]
the name should be pt_BR apparently I will change that

**Review by Dreamlinerm — APPROVED** [review]
Apparently the filename should be pt_BR, but I will change that

**Comment by Dreamlinerm** [comment]
I will add the new language on the next version

**Comment by andercard0** [comment]
> I will add the new language on the next version

No problem. I'll keep it updated as needed.

In the list you mention the language inclusion there is a typo it is Brazilian Portuguese 😜

**Pull request merged**
